name: AreaGamemodes
main: AreaGamemodes\Main
version: 0.1.1
api: [1.12.0]

load: STARTUP
author: Rspuds
editor: Skull3x
description: Applys gamemodes useing areas
commands:
        ag:
            description: All area gamemodes commands
            usage: "/ag <command>"
            permisstion: ag.commands.ag
permissions:
        ag.command.ag:
                default: true
                description: "runs all commands"
